version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  preview:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
        node-version: '16.13'
      - run: npm i
      - run: npm run preview
workflows:
  version: 2
  build_preview:
    jobs:
      - preview
