version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  preview:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: yarn
      - run: npm i -g vercel
      - run: yarn preview
workflows:
  version: 2
  build_preview:
    jobs:
      - preview
