version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  preview:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm i -g vercel
      - run: npm run preview
workflows:
  version: 2
  build_preview:
    jobs:
      - preview
