version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  preview:
    executor:
      name: node/default
      tag: '14'
    steps:
      - run:
        command: npm i -g vercel
        name: Install Vercel CLI 
      - run:
        name: "Build Vercel Preview Env"
        command: yarn preview