version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  preview:
    executor:
      name: node/default
      tag: '14'
    steps:
      - run:
        command: |
          if [[ $(which vercel) == "" ]]; then
            npm i -g vercel
          else
            echo "Vercel is already installed. No operation was performed."
          fi
        name: Install Vercel CLI (If not installed)
      - run:
        name: "Build Vercel Preview Env"
        command: yarn preview